### ISSUE TITLE
PPM JIRA Adapter suffers JSON Parse error on JIRA-stock label field

### ISSUE THREAD

**Issue by solzun** [MicroFocus/ppm-jira-connector#42]
In the class https://github.com/MicroFocus/ppm-jira-connector/blob/master/src/com/ppm/integration/agilesdk/connector/jira/util/dm/AgileEntityUtils.java there is a section of method code on line 100 to try to cast each field to a JSON object, if it cannot be cast it will then ignore that field (this line is also marked by what appears to be an internally-tracked defect ("Fix QCCR1L68982").

This works fine with the exception of JIRA's built-in labels field to hold tags. In the REST API endpoint for retrieving a JIRA issue in JSON (https://server/jira01/rest/api/2/issue/<issue_key>), the labels field is represented as such (an example of one label):
**- "labels": ["somelabel"],**

Because this is surrounded in brackets, I assume the JSON cast thinks it should be valid JSON and then errors out because it's not valid JSON upon cast:
**Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.json.JSONObject
        at com.ppm.integration.agilesdk.connector.jira.util.dm.AgileEntityUtils.getAgileEntityFromIssueJSon(AgileEntityUtils.java:100)**

Most customers won't see this since the PPM Adapter probably doesn't allow for sync of labels to JIRA, but is exposed when customers use workflow post-functions to trigger field updates after a JIRA issue is created by the PPM Adapter (using JSU or ScriptRunner, etc.), which the PPM Adapter then reads back after issue creation and dies on.
Possibly fix by hardcoding a check against the **labels** JIRA field or by putting in an additional guard to prevent cast errors (and ignore if it fails to cast.)

**Comment by etiennec** [comment]
Thanks a lot for the info. That part about post-function workflow is indeed not something we have in our test cases. We'll get that fix in this repo and also in the Jira Cloud repo (https://github.com/MicroFocus/ppm-jira-cloud-connector). The possible fixes are really appreciated!

**Comment by etiennec** [comment]
Hi Solzun,

There are conflicting statements in your message - you're pointing at the right place in the code with the error, but the error you're providing refer to a ClassCastException at line 100, which is exactly where the cast was before we added the code that checks this (i.e. QCCR1L68982).
You can find the commit here:
https://github.com/MicroFocus/ppm-jira-connector/commit/7a66d85b6f120e7646fb2025df3c6605836dcfc0

So what I assume is that you're running with an old version of the jira connector that doesn't include that fix.

It turns out that we only included that fix in the version of the connector that is bundled in recent PPM versions (9.60+), but haven't released a version of the connector that includes this fix here on GitHub. I'll address this right away.

**Comment by etiennec** [comment]
New version published here with the fix: https://github.com/MicroFocus/ppm-jira-connector/releases/tag/v2.1

No need to do a new released on repo #ppm-jira-cloud-connector, the release published already includes the fix since it was forked & released after that commit. 

Closing Issue, feel free to reopen if you still experience the problem after deploying v2.1 release.

**Comment by solzun** [comment]
@etiennec Excellent, thanks for the quick response. And you are correct, I was just basing the issue off the latest code posted to this repo on master (I believe we are using the bundled-in 2.0.) Great job!
